/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.service;

import com.vgates.customerportal.controller.MasterServiceController;
import com.vgates.customerportal.controller.UserDetailController;
import com.vgates.customerportal.model.MasterService;
import com.vgates.customerportal.model.UserDetail;
import com.vgates.customerportal.util.MethodResult;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Chamith
 */
public class ServiceMainForm extends javax.swing.JPanel {

    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");

    private final UserDetailController userDetailController;
    private final MasterServiceController serviceController;

    private final DefaultTableModel defaultServiceTableModel;

    private UserDetail userDetail;

    /**
     * Creates new form ServiceMainForm
     */
    public ServiceMainForm() {
        initComponents();
        setSize(800, 550);

        userDetailController = new UserDetailController();
        serviceController = new MasterServiceController();

        userDetail = userDetailController.findUserDetailForActiveLogin();

        defaultServiceTableModel = (DefaultTableModel) tblServiceDetail.getModel();
        defaultServiceTableModel.setRowCount(0);

        txtNewCost.setText("00.00");
        txtNewDiscount.setText("00.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceMain = new javax.swing.JLabel();
        tabServiceMain = new javax.swing.JTabbedPane();
        panelNewService = new javax.swing.JPanel();
        lblNewServiceMain = new javax.swing.JLabel();
        lblNewServiceName = new javax.swing.JLabel();
        txtNewServiceName = new javax.swing.JTextField();
        lblNewServiceCategory = new javax.swing.JLabel();
        txtNewServiceCategory = new javax.swing.JTextField();
        lblNewdesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNewDesc = new javax.swing.JTextArea();
        lblNewCost = new javax.swing.JLabel();
        txtNewCost = new javax.swing.JFormattedTextField();
        lblNewDiscount = new javax.swing.JLabel();
        txtNewDiscount = new javax.swing.JFormattedTextField();
        btnCancelAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        panelFindService = new javax.swing.JPanel();
        lblSearchServiceMain = new javax.swing.JLabel();
        txtFindServiceName = new javax.swing.JTextField();
        txtFindCategory = new javax.swing.JTextField();
        lblFindCategory = new javax.swing.JLabel();
        lblFindServiceName = new javax.swing.JLabel();
        btnCancelSearch = new javax.swing.JButton();
        btnSearchService = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServiceDetail = new javax.swing.JTable();
        panelUpdateService = new javax.swing.JPanel();

        lblServiceMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblServiceMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceMain.setText("Service Details");

        tabServiceMain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblNewServiceMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewServiceMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewServiceMain.setText("New Service Details");

        lblNewServiceName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewServiceName.setText("Service");

        txtNewServiceName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewServiceNameActionPerformed(evt);
            }
        });

        lblNewServiceCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewServiceCategory.setText("Category");

        txtNewServiceCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewServiceCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewServiceCategoryActionPerformed(evt);
            }
        });

        lblNewdesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewdesc.setText("Description");

        txtNewDesc.setColumns(20);
        txtNewDesc.setRows(5);
        jScrollPane1.setViewportView(txtNewDesc);

        lblNewCost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCost.setText("Cost");

        txtNewCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblNewDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewDiscount.setText("Discount");

        txtNewDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewDiscount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnCancelAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save Service Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewServiceLayout = new javax.swing.GroupLayout(panelNewService);
        panelNewService.setLayout(panelNewServiceLayout);
        panelNewServiceLayout.setHorizontalGroup(
            panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewServiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(panelNewServiceLayout.createSequentialGroup()
                        .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNewServiceLayout.createSequentialGroup()
                                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNewServiceCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(lblNewServiceName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewServiceCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtNewServiceName)))
                            .addGroup(panelNewServiceLayout.createSequentialGroup()
                                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNewDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewdesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(lblNewCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNewDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelNewServiceLayout.setVerticalGroup(
            panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewServiceMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewServiceName)
                    .addComponent(txtNewServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewServiceCategory)
                    .addComponent(txtNewServiceCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewdesc))
                .addGap(18, 18, 18)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewCost))
                .addGap(18, 18, 18)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewDiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(panelNewServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelAdd)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        tabServiceMain.addTab("New Service Details", panelNewService);

        lblSearchServiceMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchServiceMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchServiceMain.setText("Service Details");

        txtFindServiceName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindServiceNameActionPerformed(evt);
            }
        });

        txtFindCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCategoryActionPerformed(evt);
            }
        });

        lblFindCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindCategory.setText("Category");

        lblFindServiceName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindServiceName.setText("Service");

        btnCancelSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelSearch.setText("Cancel");
        btnCancelSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSearchActionPerformed(evt);
            }
        });

        btnSearchService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchService.setText("Search Service Details");
        btnSearchService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchServiceActionPerformed(evt);
            }
        });

        tblServiceDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service", "Category", "Cost", "Discount", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblServiceDetail);
        if (tblServiceDetail.getColumnModel().getColumnCount() > 0) {
            tblServiceDetail.getColumnModel().getColumn(0).setResizable(false);
            tblServiceDetail.getColumnModel().getColumn(1).setResizable(false);
            tblServiceDetail.getColumnModel().getColumn(2).setResizable(false);
            tblServiceDetail.getColumnModel().getColumn(3).setResizable(false);
            tblServiceDetail.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelFindServiceLayout = new javax.swing.GroupLayout(panelFindService);
        panelFindService.setLayout(panelFindServiceLayout);
        panelFindServiceLayout.setHorizontalGroup(
            panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearchServiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(panelFindServiceLayout.createSequentialGroup()
                        .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFindCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFindServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFindCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtFindServiceName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFindServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchService)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFindServiceLayout.setVerticalGroup(
            panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchServiceMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindServiceName)
                    .addComponent(txtFindServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCategory)
                    .addComponent(txtFindCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFindServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchService)
                    .addComponent(btnCancelSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        tabServiceMain.addTab("Search Service Details", panelFindService);

        javax.swing.GroupLayout panelUpdateServiceLayout = new javax.swing.GroupLayout(panelUpdateService);
        panelUpdateService.setLayout(panelUpdateServiceLayout);
        panelUpdateServiceLayout.setHorizontalGroup(
            panelUpdateServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelUpdateServiceLayout.setVerticalGroup(
            panelUpdateServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        tabServiceMain.addTab("Update Service Details", panelUpdateService);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(tabServiceMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblServiceMain, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabServiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewServiceNameActionPerformed

    }//GEN-LAST:event_txtNewServiceNameActionPerformed

    private void txtNewServiceCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewServiceCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewServiceCategoryActionPerformed

    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        txtNewCost.setText("00.00");
        txtNewDiscount.setText("00.00");
        txtNewServiceCategory.setText("");
        txtNewServiceName.setText("");
        txtNewDesc.setText("");
    }//GEN-LAST:event_btnCancelAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this Service...?", "Add New Service", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responce == JOptionPane.YES_OPTION) {
            MasterService service = new MasterService();
            service.setActive(Boolean.TRUE);
            service.setCreatedBy(userDetail.getUserName());
            service.setCreatedDate(new Date());
            service.setCategory(txtNewServiceCategory.getText());
            service.setCost(Double.parseDouble(txtNewCost.getText()));
            service.setDescription(txtNewDesc.getText());
            service.setDiscount(Double.parseDouble(txtNewDiscount.getText()));
            service.setServiceName(txtNewServiceName.getText());

            MethodResult result = serviceController.addNewServiceDetail(service);
            if (result.isOk()) {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Service", JOptionPane.INFORMATION_MESSAGE);
                txtNewCost.setText("00.00");
                txtNewDiscount.setText("00.00");
                txtNewServiceCategory.setText("");
                txtNewServiceName.setText("");
                txtNewDesc.setText("");
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Service", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFindServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindServiceNameActionPerformed

    private void txtFindCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCategoryActionPerformed

    private void btnCancelSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSearchActionPerformed
        defaultServiceTableModel.setRowCount(0);
    }//GEN-LAST:event_btnCancelSearchActionPerformed

    private void btnSearchServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchServiceActionPerformed
        defaultServiceTableModel.setRowCount(0);
        List<MasterService> serviceList = serviceController.searchService(txtFindServiceName.getText(), txtFindCategory.getText());
        if (serviceList != null) {
            serviceList.forEach(e -> {
                Object rowData[] = {e.getServiceName(), e.getCategory(),  e.getCost(), e.getDiscount(), e.getDescription()};
                defaultServiceTableModel.addRow(rowData);
            });
        }
    }//GEN-LAST:event_btnSearchServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelSearch;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchService;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFindCategory;
    private javax.swing.JLabel lblFindServiceName;
    private javax.swing.JLabel lblNewCost;
    private javax.swing.JLabel lblNewDiscount;
    private javax.swing.JLabel lblNewServiceCategory;
    private javax.swing.JLabel lblNewServiceMain;
    private javax.swing.JLabel lblNewServiceName;
    private javax.swing.JLabel lblNewdesc;
    private javax.swing.JLabel lblSearchServiceMain;
    private javax.swing.JLabel lblServiceMain;
    private javax.swing.JPanel panelFindService;
    private javax.swing.JPanel panelNewService;
    private javax.swing.JPanel panelUpdateService;
    private javax.swing.JTabbedPane tabServiceMain;
    private javax.swing.JTable tblServiceDetail;
    private javax.swing.JTextField txtFindCategory;
    private javax.swing.JTextField txtFindServiceName;
    private javax.swing.JFormattedTextField txtNewCost;
    private javax.swing.JTextArea txtNewDesc;
    private javax.swing.JFormattedTextField txtNewDiscount;
    private javax.swing.JTextField txtNewServiceCategory;
    private javax.swing.JTextField txtNewServiceName;
    // End of variables declaration//GEN-END:variables

    public UserDetail getUserDetail() {
        return userDetail;
    }

    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }
}
