/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.customer;

import com.vgates.customerportal.controller.CustomerDetailController;
import com.vgates.customerportal.model.CustomerDetail;

import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Chamith
 */
public class CustomerMainForm extends javax.swing.JPanel {

    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private CustomerDetailController customerDetailController;

    /**
     * Creates new form CustomerMainForm
     */
    public CustomerMainForm() {
        initComponents();
        setSize(800, 550);
        txtNewDob.setFormats(simpleDateFormat);
        radioBtnMale.setSelected(true);
        customerDetailController = new CustomerDetailController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        lblCustMain = new javax.swing.JLabel();
        tabCustomerDetail = new javax.swing.JTabbedPane();
        panelNewCustomer = new javax.swing.JPanel();
        lblNewCustRef = new javax.swing.JLabel();
        lblNewCustMain = new javax.swing.JLabel();
        txtNewCustRef = new javax.swing.JTextField();
        lblNewCustName = new javax.swing.JLabel();
        txtNewCustName = new javax.swing.JTextField();
        txtNewNicNo = new javax.swing.JTextField();
        lblNewNicNo = new javax.swing.JLabel();
        lblNewNicNo1 = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemal = new javax.swing.JRadioButton();
        lblNewEmail = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        txtNewContactNo = new javax.swing.JTextField();
        lblNewContactNo = new javax.swing.JLabel();
        lblNewNicNo2 = new javax.swing.JLabel();
        txtNewDob = new org.jdesktop.swingx.JXDatePicker();
        lblNewAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNewAddress = new javax.swing.JTextArea();
        lblDatePattern = new javax.swing.JLabel();
        btnCancelAdd = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        panelSearchCustomer = new javax.swing.JPanel();
        lblFindCustMain = new javax.swing.JLabel();
        lblFindCustRef = new javax.swing.JLabel();
        txtFindCustRef = new javax.swing.JTextField();
        lblFindCustName = new javax.swing.JLabel();
        txtFindCustName = new javax.swing.JTextField();
        lblFindNicNo = new javax.swing.JLabel();
        txtFindNicNo = new javax.swing.JTextField();
        btnCancelFind = new javax.swing.JButton();
        btnFindCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomerDetail = new javax.swing.JTable();

        lblCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustMain.setText("Customer Details");

        tabCustomerDetail.setFocusable(false);
        tabCustomerDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblNewCustRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCustRef.setText("Customer Reference No ");

        lblNewCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewCustMain.setText("New Customer Details");

        txtNewCustRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewCustRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustRefActionPerformed(evt);
            }
        });

        lblNewCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCustName.setText("Customer Name              ");

        txtNewCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustNameActionPerformed(evt);
            }
        });

        txtNewNicNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewNicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNicNoActionPerformed(evt);
            }
        });

        lblNewNicNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewNicNo.setText("NIC No                           ");

        lblNewNicNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewNicNo1.setText("Gender                           ");

        btnGroupGender.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioBtnMale.setText("Male");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });

        btnGroupGender.add(radioBtnFemal);
        radioBtnFemal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioBtnFemal.setText("Female");
        radioBtnFemal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemalActionPerformed(evt);
            }
        });

        lblNewEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewEmail.setText("Email");

        txtNewEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });

        txtNewContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewContactNoActionPerformed(evt);
            }
        });

        lblNewContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewContactNo.setText("Contact No");

        lblNewNicNo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewNicNo2.setText("Date Of Birth");

        txtNewDob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDobActionPerformed(evt);
            }
        });

        lblNewAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewAddress.setText("Address");

        txtNewAddress.setColumns(20);
        txtNewAddress.setRows(5);
        jScrollPane1.setViewportView(txtNewAddress);

        lblDatePattern.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDatePattern.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatePattern.setText("DD-MM-YYYY");

        btnCancelAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCustomer.setText("Save Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewCustomerLayout = new javax.swing.GroupLayout(panelNewCustomer);
        panelNewCustomer.setLayout(panelNewCustomerLayout);
        panelNewCustomerLayout.setHorizontalGroup(
            panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewCustomerLayout.createSequentialGroup()
                        .addComponent(lblNewCustMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelNewCustomerLayout.createSequentialGroup()
                        .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNewAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewNicNo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewNicNo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewNicNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewCustRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewCustName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewCustName)
                            .addComponent(txtNewCustRef)
                            .addComponent(txtNewNicNo)
                            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                                .addComponent(radioBtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnFemal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNewEmail)
                            .addComponent(txtNewContactNo)
                            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                                .addComponent(txtNewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDatePattern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(78, 315, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNewCustomerLayout.setVerticalGroup(
            panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewCustMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCustRef)
                    .addComponent(txtNewCustRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCustName)
                    .addComponent(txtNewCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewNicNo)
                    .addComponent(txtNewNicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewNicNo2)
                    .addComponent(txtNewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatePattern))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewNicNo1)
                    .addComponent(radioBtnMale)
                    .addComponent(radioBtnFemal))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmail)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewContactNo)
                    .addComponent(txtNewContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnCancelAdd))
                .addContainerGap())
        );

        tabCustomerDetail.addTab("New Customer Details", panelNewCustomer);

        lblFindCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFindCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFindCustMain.setText("Search Customer Details");

        lblFindCustRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindCustRef.setText("Customer Reference No ");

        txtFindCustRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindCustRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCustRefActionPerformed(evt);
            }
        });

        lblFindCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindCustName.setText("Customer Name              ");

        txtFindCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCustNameActionPerformed(evt);
            }
        });

        lblFindNicNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindNicNo.setText("NIC No                           ");

        txtFindNicNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindNicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindNicNoActionPerformed(evt);
            }
        });

        btnCancelFind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelFind.setText("Cancel");
        btnCancelFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFindActionPerformed(evt);
            }
        });

        btnFindCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFindCustomer.setText("Search Customer");
        btnFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustomerActionPerformed(evt);
            }
        });

        tblCustomerDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ref", "Name", "NIC", "DOB", "Gender", "Email", "Contact No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCustomerDetail);
        if (tblCustomerDetail.getColumnModel().getColumnCount() > 0) {
            tblCustomerDetail.getColumnModel().getColumn(1).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(2).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(3).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(4).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(5).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(6).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout panelSearchCustomerLayout = new javax.swing.GroupLayout(panelSearchCustomer);
        panelSearchCustomer.setLayout(panelSearchCustomerLayout);
        panelSearchCustomerLayout.setHorizontalGroup(
            panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(lblFindCustMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSearchCustomerLayout.createSequentialGroup()
                        .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFindNicNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFindCustRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFindCustName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFindCustRef, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtFindCustName)
                            .addComponent(txtFindNicNo)))
                    .addGroup(panelSearchCustomerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFindCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelFind, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelSearchCustomerLayout.setVerticalGroup(
            panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFindCustMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCustRef)
                    .addComponent(txtFindCustRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCustName)
                    .addComponent(txtFindCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindNicNo)
                    .addComponent(txtFindNicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindCustomer)
                    .addComponent(btnCancelFind))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabCustomerDetail.addTab("Search Customer Details", panelSearchCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(tabCustomerDetail)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCustMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabCustomerDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewCustRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustRefActionPerformed
        txtNewCustName.requestFocus();
    }//GEN-LAST:event_txtNewCustRefActionPerformed

    private void txtNewCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustNameActionPerformed
        txtNewNicNo.requestFocus();
    }//GEN-LAST:event_txtNewCustNameActionPerformed

    private void txtNewNicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNicNoActionPerformed
        txtNewDob.requestFocus();
    }//GEN-LAST:event_txtNewNicNoActionPerformed

    private void txtNewDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDobActionPerformed
        radioBtnMale.requestFocus();
    }//GEN-LAST:event_txtNewDobActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        txtNewEmail.requestFocus();
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void radioBtnFemalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemalActionPerformed
        txtNewEmail.requestFocus();
    }//GEN-LAST:event_radioBtnFemalActionPerformed

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        txtNewContactNo.requestFocus();
    }//GEN-LAST:event_txtNewEmailActionPerformed

    private void txtNewContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewContactNoActionPerformed
        txtNewAddress.requestFocus();
    }//GEN-LAST:event_txtNewContactNoActionPerformed

    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        txtNewCustRef.setText("");
        txtNewCustName.setText("");
        txtNewNicNo.setText("");
        txtNewDob.setDate(null);
        txtNewEmail.setText("");
        txtNewContactNo.setText("");
        txtNewAddress.setText("");
        radioBtnMale.setSelected(true);
    }//GEN-LAST:event_btnCancelAddActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this Customer...?", "Add New Customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (responce == JOptionPane.YES_OPTION) {

            String gender = "Male";

            if (radioBtnMale.isSelected()) {
                gender = "Male";
            } else if (radioBtnFemal.isSelected()) {
                gender = "Female";
            }

            CustomerDetail customerDetail = new CustomerDetail();
            customerDetail.setCustomerNo(txtNewCustRef.getText());
            customerDetail.setCustomerName(txtNewCustName.getText());
            customerDetail.setNic(txtNewNicNo.getText());
            customerDetail.setDob(txtNewDob.getDate());
            customerDetail.setGender(gender);
            customerDetail.setEmail(txtNewEmail.getText());
            customerDetail.setContactNo(txtNewContactNo.getText());
            customerDetail.setAddress(txtNewAddress.getText());
            customerDetail.setCreatedDate(new Date());
            customerDetail.setActive(Boolean.TRUE);

            customerDetailController.addNewCustomerDetail(customerDetail);
        }

    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void txtFindCustRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCustRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCustRefActionPerformed

    private void txtFindCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCustNameActionPerformed

    private void txtFindNicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindNicNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindNicNoActionPerformed

    private void btnCancelFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFindActionPerformed

    private void btnFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelFind;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustMain;
    private javax.swing.JLabel lblDatePattern;
    private javax.swing.JLabel lblFindCustMain;
    private javax.swing.JLabel lblFindCustName;
    private javax.swing.JLabel lblFindCustRef;
    private javax.swing.JLabel lblFindNicNo;
    private javax.swing.JLabel lblNewAddress;
    private javax.swing.JLabel lblNewContactNo;
    private javax.swing.JLabel lblNewCustMain;
    private javax.swing.JLabel lblNewCustName;
    private javax.swing.JLabel lblNewCustRef;
    private javax.swing.JLabel lblNewEmail;
    private javax.swing.JLabel lblNewNicNo;
    private javax.swing.JLabel lblNewNicNo1;
    private javax.swing.JLabel lblNewNicNo2;
    private javax.swing.JPanel panelNewCustomer;
    private javax.swing.JPanel panelSearchCustomer;
    private javax.swing.JRadioButton radioBtnFemal;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTabbedPane tabCustomerDetail;
    private javax.swing.JTable tblCustomerDetail;
    private javax.swing.JTextField txtFindCustName;
    private javax.swing.JTextField txtFindCustRef;
    private javax.swing.JTextField txtFindNicNo;
    private javax.swing.JTextArea txtNewAddress;
    private javax.swing.JTextField txtNewContactNo;
    private javax.swing.JTextField txtNewCustName;
    private javax.swing.JTextField txtNewCustRef;
    private org.jdesktop.swingx.JXDatePicker txtNewDob;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewNicNo;
    // End of variables declaration//GEN-END:variables

    public CustomerDetailController getCustomerDetailController() {
        return customerDetailController;
    }

    public void setCustomerDetailController(CustomerDetailController customerDetailController) {
        this.customerDetailController = customerDetailController;
    }
}
