/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.customer;

import com.vgates.customerportal.controller.CustomerDetailController;
import com.vgates.customerportal.controller.UserDetailController;
import com.vgates.customerportal.model.CustomerDetail;
import com.vgates.customerportal.model.UserDetail;
import com.vgates.customerportal.util.MethodResult;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * @author Chamith
 */
public class CustomerMainForm extends javax.swing.JPanel {

    private final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");

    private final CustomerDetailController customerDetailController;
    private final UserDetailController userDetailController;

    private final DefaultTableModel defaultCustTableModel;
    private CustomerDetail searchCustomer;
    private UserDetail userDetail;

    /**
     * Creates new form CustomerMainForm
     */
    public CustomerMainForm() {
        initComponents();
        setSize(800, 550);

        txtNewCustRef.setEnabled(false);

        customerDetailController = new CustomerDetailController();
        userDetailController = new UserDetailController();

        defaultCustTableModel = (DefaultTableModel) tblCustomerDetail.getModel();
        defaultCustTableModel.setRowCount(0);

        userDetail = userDetailController.findUserDetailForActiveLogin();
        txtNewCustRef.setText(customerDetailController.newCustomerRef());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        btnGroupGenderUpdate = new javax.swing.ButtonGroup();
        lblCustMain = new javax.swing.JLabel();
        tabCustomerDetail = new javax.swing.JTabbedPane();
        panelNewCustomer = new javax.swing.JPanel();
        lblNewCustRef = new javax.swing.JLabel();
        lblNewCustMain = new javax.swing.JLabel();
        txtNewCustRef = new javax.swing.JTextField();
        lblNewCustName = new javax.swing.JLabel();
        txtNewCustName = new javax.swing.JTextField();
        txtNewNicNo = new javax.swing.JTextField();
        lblNewNicNo = new javax.swing.JLabel();
        lblNewEmail = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        txtNewContactNo = new javax.swing.JTextField();
        lblNewContactNo = new javax.swing.JLabel();
        lblNewAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNewAddress = new javax.swing.JTextArea();
        btnCancelAdd = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        lblContactNoPatten2 = new javax.swing.JLabel();
        panelSearchCustomer = new javax.swing.JPanel();
        lblFindCustMain = new javax.swing.JLabel();
        lblFindCustRef = new javax.swing.JLabel();
        txtFindCustRef = new javax.swing.JTextField();
        lblFindCustName = new javax.swing.JLabel();
        txtFindCustName = new javax.swing.JTextField();
        btnCancelFind = new javax.swing.JButton();
        btnFindCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomerDetail = new javax.swing.JTable();
        panelUpdateCustomer = new javax.swing.JPanel();
        lblUpdateCustRef = new javax.swing.JLabel();
        lblUpdateCustName = new javax.swing.JLabel();
        lblUpdateEmail = new javax.swing.JLabel();
        lblUpdateContactNo = new javax.swing.JLabel();
        lblUpdateAddress = new javax.swing.JLabel();
        txtUpdateCustRef = new javax.swing.JTextField();
        txtUpdateCustName = new javax.swing.JTextField();
        txtUpdateEmail = new javax.swing.JTextField();
        txtUpdateContactNo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtUpdateAddress = new javax.swing.JTextArea();
        lblCustUpdate = new javax.swing.JLabel();
        btnSearchCustomer = new javax.swing.JButton();
        lblContactNoPatten1 = new javax.swing.JLabel();
        btnDeleteCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();

        lblCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustMain.setText("Customer Details");

        tabCustomerDetail.setFocusable(false);
        tabCustomerDetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblNewCustRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCustRef.setText("Customer Reference No ");

        lblNewCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewCustMain.setText("New Customer Details");

        txtNewCustRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewCustRef.setEnabled(false);
        txtNewCustRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustRefActionPerformed(evt);
            }
        });

        lblNewCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCustName.setText("Customer Name              ");

        txtNewCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustNameActionPerformed(evt);
            }
        });

        txtNewNicNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewNicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNicNoActionPerformed(evt);
            }
        });

        lblNewNicNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewNicNo.setText("NIC No                           ");

        lblNewEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewEmail.setText("Email");

        txtNewEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });

        txtNewContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewContactNoActionPerformed(evt);
            }
        });

        lblNewContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewContactNo.setText("Contact No");

        lblNewAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewAddress.setText("Address");

        txtNewAddress.setColumns(20);
        txtNewAddress.setRows(5);
        jScrollPane1.setViewportView(txtNewAddress);

        btnCancelAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCustomer.setText("Save Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        lblContactNoPatten2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblContactNoPatten2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactNoPatten2.setText("07XXXXXXXX");

        javax.swing.GroupLayout panelNewCustomerLayout = new javax.swing.GroupLayout(panelNewCustomer);
        panelNewCustomer.setLayout(panelNewCustomerLayout);
        panelNewCustomerLayout.setHorizontalGroup(
            panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewCustomerLayout.createSequentialGroup()
                        .addComponent(lblNewCustMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelNewCustomerLayout.createSequentialGroup()
                        .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNewAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewNicNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewCustRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewCustName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewCustName)
                            .addComponent(txtNewCustRef)
                            .addComponent(txtNewNicNo)
                            .addComponent(txtNewEmail)
                            .addComponent(jScrollPane1)
                            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                                .addComponent(txtNewContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContactNoPatten2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addGap(78, 304, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNewCustomerLayout.setVerticalGroup(
            panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewCustMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCustRef)
                    .addComponent(txtNewCustRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCustName)
                    .addComponent(txtNewCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewNicNo)
                    .addComponent(txtNewNicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmail)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewContactNo)
                        .addComponent(txtNewContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblContactNoPatten2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panelNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnCancelAdd))
                .addGap(167, 167, 167))
        );

        tabCustomerDetail.addTab("New Customer Details", panelNewCustomer);

        lblFindCustMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFindCustMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFindCustMain.setText("Search Customer Details");

        lblFindCustRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindCustRef.setText("Customer Reference No ");

        txtFindCustRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindCustRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCustRefActionPerformed(evt);
            }
        });

        lblFindCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFindCustName.setText("Customer Name              ");

        txtFindCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFindCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindCustNameActionPerformed(evt);
            }
        });

        btnCancelFind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelFind.setText("Cancel");
        btnCancelFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFindActionPerformed(evt);
            }
        });

        btnFindCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFindCustomer.setText("Search Customer");
        btnFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustomerActionPerformed(evt);
            }
        });

        tblCustomerDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ref", "Name", "DOB", "Email", "Contact No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCustomerDetail);
        if (tblCustomerDetail.getColumnModel().getColumnCount() > 0) {
            tblCustomerDetail.getColumnModel().getColumn(0).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(1).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(2).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(3).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(4).setResizable(false);
            tblCustomerDetail.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panelSearchCustomerLayout = new javax.swing.GroupLayout(panelSearchCustomer);
        panelSearchCustomer.setLayout(panelSearchCustomerLayout);
        panelSearchCustomerLayout.setHorizontalGroup(
            panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(lblFindCustMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSearchCustomerLayout.createSequentialGroup()
                        .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFindCustRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFindCustName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFindCustRef, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtFindCustName)))
                    .addGroup(panelSearchCustomerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFindCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelFind, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelSearchCustomerLayout.setVerticalGroup(
            panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFindCustMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCustRef)
                    .addComponent(txtFindCustRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFindCustName)
                    .addComponent(txtFindCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindCustomer)
                    .addComponent(btnCancelFind))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabCustomerDetail.addTab("Search Customer Details", panelSearchCustomer);

        lblUpdateCustRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUpdateCustRef.setText("Customer Reference No ");

        lblUpdateCustName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUpdateCustName.setText("Customer Name              ");

        lblUpdateEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUpdateEmail.setText("Email");

        lblUpdateContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUpdateContactNo.setText("Contact No");

        lblUpdateAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUpdateAddress.setText("Address");

        txtUpdateCustRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUpdateCustRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCustRefActionPerformed(evt);
            }
        });

        txtUpdateCustName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUpdateCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCustNameActionPerformed(evt);
            }
        });

        txtUpdateEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUpdateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateEmailActionPerformed(evt);
            }
        });

        txtUpdateContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUpdateContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateContactNoActionPerformed(evt);
            }
        });

        txtUpdateAddress.setColumns(20);
        txtUpdateAddress.setRows(5);
        jScrollPane3.setViewportView(txtUpdateAddress);

        lblCustUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustUpdate.setText("Customer Details");

        btnSearchCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchCustomer.setText("Search Customer");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        lblContactNoPatten1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblContactNoPatten1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactNoPatten1.setText("07XXXXXXXX");

        btnDeleteCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteCustomer.setText("Delete Customer");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateCustomer.setText("Update Customer");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateCustomerLayout = new javax.swing.GroupLayout(panelUpdateCustomer);
        panelUpdateCustomer.setLayout(panelUpdateCustomerLayout);
        panelUpdateCustomerLayout.setHorizontalGroup(
            panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateCustomerLayout.createSequentialGroup()
                        .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUpdateAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateCustRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateCustName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpdateCustName)
                            .addComponent(txtUpdateCustRef)
                            .addComponent(txtUpdateEmail)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUpdateCustomerLayout.createSequentialGroup()
                                .addComponent(txtUpdateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContactNoPatten1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchCustomer)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(lblCustUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateCustomerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteCustomer)))
                .addContainerGap())
        );
        panelUpdateCustomerLayout.setVerticalGroup(
            panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCustRef)
                    .addComponent(txtUpdateCustRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateCustName)
                    .addComponent(txtUpdateCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateEmail)
                    .addComponent(txtUpdateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateContactNo)
                    .addComponent(txtUpdateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactNoPatten1))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateAddress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(panelUpdateCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCustomer)
                    .addComponent(btnUpdateCustomer))
                .addContainerGap())
        );

        tabCustomerDetail.addTab("Update Customer Details", panelUpdateCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCustMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tabCustomerDetail))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCustMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabCustomerDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewCustRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustRefActionPerformed
        txtNewCustName.requestFocus();
    }//GEN-LAST:event_txtNewCustRefActionPerformed

    private void txtNewCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustNameActionPerformed
        txtNewNicNo.requestFocus();
    }//GEN-LAST:event_txtNewCustNameActionPerformed

    private void txtNewNicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNicNoActionPerformed
        txtNewEmail.requestFocus();
    }//GEN-LAST:event_txtNewNicNoActionPerformed

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        txtNewContactNo.requestFocus();
    }//GEN-LAST:event_txtNewEmailActionPerformed

    private void txtNewContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewContactNoActionPerformed
        txtNewAddress.requestFocus();
    }//GEN-LAST:event_txtNewContactNoActionPerformed

    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        txtNewCustRef.setText("");
        txtNewCustName.setText("");
        txtNewNicNo.setText("");

        txtNewEmail.setText("");
        txtNewContactNo.setText("");
        txtNewAddress.setText("");

    }//GEN-LAST:event_btnCancelAddActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this Customer...?", "Add New Customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (responce == JOptionPane.YES_OPTION) {


            CustomerDetail customerDetail = new CustomerDetail();
            customerDetail.setCustomerNo(txtNewCustRef.getText());
            customerDetail.setCustomerName(txtNewCustName.getText());
            customerDetail.setEmail(txtNewEmail.getText());
            customerDetail.setContactNo(txtNewContactNo.getText());
            customerDetail.setAddress(txtNewAddress.getText());
            customerDetail.setCreatedDate(new Date());
            customerDetail.setCreatedBy(userDetail.getUserName());
            customerDetail.setActive(Boolean.TRUE);

            MethodResult result = customerDetailController.addNewCustomerDetail(customerDetail);
            if (result.isOk()) {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Customer", JOptionPane.INFORMATION_MESSAGE);
                txtNewCustRef.setText(customerDetailController.newCustomerRef());
                txtNewCustName.setText("");
                txtNewNicNo.setText("");

                txtNewEmail.setText("");
                txtNewContactNo.setText("");
                txtNewAddress.setText("");
 
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Customer", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void txtFindCustRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCustRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCustRefActionPerformed

    private void txtFindCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindCustNameActionPerformed

    private void btnCancelFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFindActionPerformed
        defaultCustTableModel.setRowCount(0);
        txtFindCustName.setText("");
        txtFindCustRef.setText("");
    }//GEN-LAST:event_btnCancelFindActionPerformed

    private void btnFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustomerActionPerformed
        defaultCustTableModel.setRowCount(0);
        List<CustomerDetail> customerList = customerDetailController.getActiveCustomerList(txtFindCustName.getText(), txtFindCustRef.getText());
        if (customerList != null) {
            customerList.forEach(e -> {
                Object rows[] = {e.getCustomerNo(), e.getCustomerName(), e.getEmail(), e.getContactNo(), e.getAddress()};
                defaultCustTableModel.addRow(rows);
            });
        }
    }//GEN-LAST:event_btnFindCustomerActionPerformed

    private void txtUpdateCustRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCustRefActionPerformed

    }//GEN-LAST:event_txtUpdateCustRefActionPerformed

    private void txtUpdateCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCustNameActionPerformed

    private void txtUpdateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateEmailActionPerformed

    private void txtUpdateContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateContactNoActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        searchCustomer = customerDetailController.searchCustomerByCustomerNo(txtUpdateCustRef.getText());
        if (searchCustomer != null) {
            txtUpdateCustName.setText(searchCustomer.getCustomerName());

            txtUpdateEmail.setText(searchCustomer.getEmail());
            txtUpdateContactNo.setText(searchCustomer.getContactNo());
            txtUpdateAddress.setText(searchCustomer.getAddress());

        } else {
            JOptionPane.showMessageDialog(this, "Cannot Find Customer details....!", "Search Customer", JOptionPane.ERROR_MESSAGE);
            txtUpdateCustName.setText("");
            txtUpdateEmail.setText("");
            txtUpdateContactNo.setText("");
            txtUpdateAddress.setText("");
        }
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        if (searchCustomer != null) {
            int res = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record...?", "Delete Customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (res == JOptionPane.YES_OPTION) {
                MethodResult result = customerDetailController.changeCustomerStatus(Boolean.FALSE, searchCustomer.getId());
                if (result.isOk()) {
                    JOptionPane.showMessageDialog(this, "Customer Detail Successfully deleted...!", "Delete Customer", JOptionPane.INFORMATION_MESSAGE);
                    txtUpdateCustName.setText("");
                    txtUpdateEmail.setText("");
                    txtUpdateContactNo.setText("");
                    txtUpdateAddress.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Customer Detail delete failed...!", "Delete Customer", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this Customer...?", "Update Customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (responce == JOptionPane.YES_OPTION) {

            searchCustomer.setCustomerNo(txtUpdateCustRef.getText());
            searchCustomer.setCustomerName(txtUpdateCustName.getText());

            searchCustomer.setEmail(txtUpdateEmail.getText());
            searchCustomer.setContactNo(txtUpdateContactNo.getText());
            searchCustomer.setAddress(txtUpdateAddress.getText());
            searchCustomer.setActive(Boolean.TRUE);

            MethodResult result = customerDetailController.updateCustomerDetail(searchCustomer);
            if (result.isOk()) {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Update Customer", JOptionPane.INFORMATION_MESSAGE);
                txtUpdateCustRef.setText("");
                txtUpdateCustName.setText("");
                txtUpdateEmail.setText("");
                txtUpdateContactNo.setText("");
                txtUpdateAddress.setText("");
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Update Customer", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelFind;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.ButtonGroup btnGroupGenderUpdate;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblContactNoPatten1;
    private javax.swing.JLabel lblContactNoPatten2;
    private javax.swing.JLabel lblCustMain;
    private javax.swing.JLabel lblCustUpdate;
    private javax.swing.JLabel lblFindCustMain;
    private javax.swing.JLabel lblFindCustName;
    private javax.swing.JLabel lblFindCustRef;
    private javax.swing.JLabel lblNewAddress;
    private javax.swing.JLabel lblNewContactNo;
    private javax.swing.JLabel lblNewCustMain;
    private javax.swing.JLabel lblNewCustName;
    private javax.swing.JLabel lblNewCustRef;
    private javax.swing.JLabel lblNewEmail;
    private javax.swing.JLabel lblNewNicNo;
    private javax.swing.JLabel lblUpdateAddress;
    private javax.swing.JLabel lblUpdateContactNo;
    private javax.swing.JLabel lblUpdateCustName;
    private javax.swing.JLabel lblUpdateCustRef;
    private javax.swing.JLabel lblUpdateEmail;
    private javax.swing.JPanel panelNewCustomer;
    private javax.swing.JPanel panelSearchCustomer;
    private javax.swing.JPanel panelUpdateCustomer;
    private javax.swing.JTabbedPane tabCustomerDetail;
    private javax.swing.JTable tblCustomerDetail;
    private javax.swing.JTextField txtFindCustName;
    private javax.swing.JTextField txtFindCustRef;
    private javax.swing.JTextArea txtNewAddress;
    private javax.swing.JTextField txtNewContactNo;
    private javax.swing.JTextField txtNewCustName;
    private javax.swing.JTextField txtNewCustRef;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewNicNo;
    private javax.swing.JTextArea txtUpdateAddress;
    private javax.swing.JTextField txtUpdateContactNo;
    private javax.swing.JTextField txtUpdateCustName;
    private javax.swing.JTextField txtUpdateCustRef;
    private javax.swing.JTextField txtUpdateEmail;
    // End of variables declaration//GEN-END:variables

    public CustomerDetail getSearchCustomer() {
        return searchCustomer;
    }

    public void setSearchCustomer(CustomerDetail searchCustomer) {
        this.searchCustomer = searchCustomer;
    }

    public UserDetail getUserDetail() {
        return userDetail;
    }

    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }
}
