/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.main;

import com.vgates.customerportal.controller.UserDetailController;
import com.vgates.customerportal.view.customer.CustomerMainForm;
import com.vgates.customerportal.view.service.ServiceMainForm;
import org.apache.log4j.Logger;

import javax.swing.*;

/**
 * @author Chamith
 */
public class MainWindowForm extends javax.swing.JFrame {

    final static Logger LOGGER = Logger.getLogger(MainWindowForm.class);
    private UserDetailController userDetailController;

    /**
     * Creates new form MainWindowForm
     */
    public MainWindowForm() {
        userDetailController = new UserDetailController();
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelMain = new javax.swing.JPanel();
        panelMainBtn = new javax.swing.JPanel();
        btnCustomerMain = new javax.swing.JButton();
        btnServiceMain = new javax.swing.JButton();
        panelMainView = new org.jdesktop.swingx.JXImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelMain.setMaximumSize(new java.awt.Dimension(1000, 600));
        panelMain.setMinimumSize(new java.awt.Dimension(1000, 600));
        panelMain.setPreferredSize(new java.awt.Dimension(1000, 600));

        panelMainBtn.setMaximumSize(new java.awt.Dimension(200, 600));
        panelMainBtn.setMinimumSize(new java.awt.Dimension(200, 600));
        panelMainBtn.setPreferredSize(new java.awt.Dimension(200, 600));

        btnCustomerMain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCustomerMain.setText("Customer Details");
        btnCustomerMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerMainActionPerformed(evt);
            }
        });

        btnServiceMain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnServiceMain.setText("Service Details");
        btnServiceMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainBtnLayout = new javax.swing.GroupLayout(panelMainBtn);
        panelMainBtn.setLayout(panelMainBtnLayout);
        panelMainBtnLayout.setHorizontalGroup(
            panelMainBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustomerMain, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnServiceMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainBtnLayout.setVerticalGroup(
            panelMainBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainBtnLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCustomerMain)
                .addGap(18, 18, 18)
                .addComponent(btnServiceMain)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        panelMainView.setMaximumSize(new java.awt.Dimension(800, 600));
        panelMainView.setMinimumSize(new java.awt.Dimension(800, 600));
        panelMainView.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout panelMainViewLayout = new javax.swing.GroupLayout(panelMainView);
        panelMainView.setLayout(panelMainViewLayout);
        panelMainViewLayout.setHorizontalGroup(
            panelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelMainViewLayout.setVerticalGroup(
            panelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelMainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMainView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit Customer Portal...?", "Exiting", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responce == JOptionPane.YES_OPTION) {
            boolean logoutSuccess = userDetailController.logoutAllUser();
            if(logoutSuccess){
                System.exit(0);
            }else{
                JOptionPane.showMessageDialog(this, "Failed...!");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCustomerMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerMainActionPerformed
        CustomerMainForm view = new CustomerMainForm();
        view.setSize(panelMainView.getSize());
        panelMainView.removeAll();
        panelMainView.add(view);
        panelMainView.revalidate();
        panelMainView.repaint();
    }//GEN-LAST:event_btnCustomerMainActionPerformed

    private void btnServiceMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceMainActionPerformed
        ServiceMainForm view = new ServiceMainForm();
        view.setSize(panelMainView.getSize());
        panelMainView.removeAll();
        panelMainView.add(view);
        panelMainView.revalidate();
        panelMainView.repaint();
    }//GEN-LAST:event_btnServiceMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerMain;
    private javax.swing.JButton btnServiceMain;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMainBtn;
    private org.jdesktop.swingx.JXImagePanel panelMainView;
    // End of variables declaration//GEN-END:variables

    public UserDetailController getUserDetailController() {
        return userDetailController;
    }

    public void setUserDetailController(UserDetailController userDetailController) {
        this.userDetailController = userDetailController;
    }
}
