/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.invoice;

import com.vgates.customerportal.controller.UserDetailController;
import com.vgates.customerportal.model.Invoice;
import com.vgates.customerportal.model.UserDetail;
import com.vgates.customerportal.util.MethodResult;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Chamith
 */
public class InvoiceMainForm extends javax.swing.JPanel {

    private final UserDetailController userDetailController;

    private final DefaultTableModel defaultServiceTableModel;

    private UserDetail userDetail;
    private Invoice invoice;

    /**
     * Creates new form InvoiceMainForm
     */
    public InvoiceMainForm() {
        initComponents();
        setSize(800, 550);

        userDetailController = new UserDetailController();

        userDetail = userDetailController.findUserDetailForActiveLogin();

        defaultServiceTableModel = (DefaultTableModel) tblInvoiceDetail.getModel();
        defaultServiceTableModel.setRowCount(0);

        txtNewCost.setText("00.00");
        txtNewDiscount.setText("00.00");        
        txtNewPaidAmount.setText("00.00");
        txtNewBalance.setText("00.00");
        txtNewInvoiceNo.setText("");
        txtNewDesc.setText("");

        txtSearchInvoiceDate.setText("");
        txtSearchInvoiceNo.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInvoiceMain = new javax.swing.JLabel();
        panelSearchInvoice = new javax.swing.JTabbedPane();
        panelNewItem = new javax.swing.JPanel();
        lblNewItemMain = new javax.swing.JLabel();
        lblNewInvoiceNo = new javax.swing.JLabel();
        txtNewInvoiceNo = new javax.swing.JTextField();
        lblNewInvoiceDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNewDesc = new javax.swing.JTextArea();
        lblNewCost = new javax.swing.JLabel();
        lblNewDiscount = new javax.swing.JLabel();
        txtNewCost = new javax.swing.JFormattedTextField();
        txtNewDiscount = new javax.swing.JFormattedTextField();
        btnCancelAdd = new javax.swing.JButton();
        btnNewInvoice = new javax.swing.JButton();
        lblNewCost1 = new javax.swing.JLabel();
        txtNewPaidAmount = new javax.swing.JFormattedTextField();
        txtNewBalance = new javax.swing.JFormattedTextField();
        lblNewCost2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        txtSearchInvoiceDate = new javax.swing.JTextField();
        lblSearchInvoiceDate = new javax.swing.JLabel();
        lblSearchInvoiceNo = new javax.swing.JLabel();
        txtSearchInvoiceNo = new javax.swing.JTextField();
        lblSearchInvoice = new javax.swing.JLabel();
        btnFindInvoice = new javax.swing.JButton();
        btnCancelSearchInvoice = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoiceDetail = new javax.swing.JTable();

        lblInvoiceMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInvoiceMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoiceMain.setText("Invoice Details");

        panelSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblNewItemMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewItemMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewItemMain.setText("New Invoice");

        lblNewInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewInvoiceNo.setText("Invoice No");

        txtNewInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewInvoiceNo.setEnabled(false);
        txtNewInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewInvoiceNoActionPerformed(evt);
            }
        });

        lblNewInvoiceDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewInvoiceDesc.setText("Description");

        txtNewDesc.setColumns(20);
        txtNewDesc.setRows(5);
        jScrollPane1.setViewportView(txtNewDesc);

        lblNewCost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCost.setText("Total");

        lblNewDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewDiscount.setText("Discount");

        txtNewCost.setEditable(false);
        txtNewCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNewDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewDiscount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDiscountActionPerformed(evt);
            }
        });

        btnCancelAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        btnNewInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewInvoice.setText("Save Item");
        btnNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewInvoiceActionPerformed(evt);
            }
        });

        lblNewCost1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCost1.setText("Paid Amount");

        txtNewPaidAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewPaidAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewPaidAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNewBalance.setEditable(false);
        txtNewBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblNewCost2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCost2.setText("Balance");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout panelNewItemLayout = new javax.swing.GroupLayout(panelNewItem);
        panelNewItem.setLayout(panelNewItemLayout);
        panelNewItemLayout.setHorizontalGroup(
            panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewItemMain, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(panelNewItemLayout.createSequentialGroup()
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNewInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewInvoiceDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNewItemLayout.createSequentialGroup()
                                .addComponent(txtNewInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE))
                            .addGroup(panelNewItemLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                        .addComponent(lblNewCost2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                        .addComponent(lblNewCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNewDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtNewDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1))))
                .addGap(19, 19, 19))
        );
        panelNewItemLayout.setVerticalGroup(
            panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewItemMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewInvoiceNo)
                    .addComponent(txtNewInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewInvoiceDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewCost)
                    .addComponent(txtNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewItemLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNewDiscount))
                    .addComponent(txtNewDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCost1)
                    .addComponent(txtNewPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCost2)
                    .addComponent(txtNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelAdd)
                    .addComponent(btnNewInvoice))
                .addContainerGap())
        );

        panelSearchInvoice.addTab("New Invoice", panelNewItem);

        txtSearchInvoiceDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchInvoiceDate.setEnabled(false);
        txtSearchInvoiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInvoiceDateActionPerformed(evt);
            }
        });

        lblSearchInvoiceDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchInvoiceDate.setText("Date");

        lblSearchInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchInvoiceNo.setText("Invoice No");

        txtSearchInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchInvoiceNo.setEnabled(false);
        txtSearchInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInvoiceNoActionPerformed(evt);
            }
        });

        lblSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchInvoice.setText("Search Item Details");

        btnFindInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFindInvoice.setText("Search Item");
        btnFindInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInvoiceActionPerformed(evt);
            }
        });

        btnCancelSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelSearchInvoice.setText("Cancel");
        btnCancelSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSearchInvoiceActionPerformed(evt);
            }
        });

        tblInvoiceDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Category", "Description", "Cost", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInvoiceDetail);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSearchInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSearchInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchInvoiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtSearchInvoiceNo))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSearchInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFindInvoice)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchInvoiceNo)
                    .addComponent(txtSearchInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchInvoiceDate)
                    .addComponent(txtSearchInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindInvoice)
                    .addComponent(btnCancelSearchInvoice))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSearchInvoice.addTab("Search Invoices", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInvoiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelSearchInvoice)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInvoiceMain, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSearchInvoice))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewInvoiceNoActionPerformed

    }//GEN-LAST:event_txtNewInvoiceNoActionPerformed

    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        txtNewCost.setText("00.00");
        txtNewDiscount.setText("00.00");
        txtNewPaidAmount.setText("00.00");
        txtNewBalance.setText("00.00");
        txtNewInvoiceNo.setText("");
        txtNewDesc.setText("");
    }//GEN-LAST:event_btnCancelAddActionPerformed

    private void btnNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewInvoiceActionPerformed
        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this Invoice...?", "New Invoice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responce == JOptionPane.YES_OPTION) {
            invoice = new Invoice();
            invoice.setInvoiceNo(txtNewInvoiceNo.getText());
            invoice.setCreatedDate(new Date());
            invoice.setDescription(txtNewDesc.getText());
            invoice.setTotalAmount(Double.parseDouble(txtNewCost.getText()));
            invoice.setDiscount(Double.parseDouble(txtNewDiscount.getText()));
            invoice.setPaidAmount(Double.parseDouble(txtNewPaidAmount.getText()));
            invoice.setBalanceAmount(Double.parseDouble(txtNewBalance.getText()));

            MethodResult result = new MethodResult();
            if (result.isOk()) {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Invoice", JOptionPane.INFORMATION_MESSAGE);
                txtNewCost.setText("00.00");
                txtNewDiscount.setText("00.00");
                txtNewPaidAmount.setText("00.00");
                txtNewBalance.setText("00.00");
                txtNewInvoiceNo.setText("");
                txtNewDesc.setText("");
                invoice = new Invoice();
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Invoice", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNewInvoiceActionPerformed

    private void txtSearchInvoiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInvoiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInvoiceDateActionPerformed

    private void txtSearchInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInvoiceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInvoiceNoActionPerformed

    private void btnFindInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInvoiceActionPerformed
//        defaultServiceTableModel.setRowCount(0);
//        List<MasterInvoice> invoiceList = invoiceController.searchInvoiceByNameAndCategory(txtSearchInvoiceName.getText(), txtSearchInvoiceDate.getText());
//        if (invoiceList != null) {
//            invoiceList.forEach(e -> {
//                Object rowData[] = {e.getInvoiceName(), e.getCategory(), e.getDescription(), e.getCost(), e.getDiscount()};
//                defaultServiceTableModel.addRow(rowData);
//            });
//        }
    }//GEN-LAST:event_btnFindInvoiceActionPerformed

    private void btnCancelSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSearchInvoiceActionPerformed
        defaultServiceTableModel.setRowCount(0);
    }//GEN-LAST:event_btnCancelSearchInvoiceActionPerformed

    private void txtNewDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewDiscountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelSearchInvoice;
    private javax.swing.JButton btnFindInvoice;
    private javax.swing.JButton btnNewInvoice;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInvoiceMain;
    private javax.swing.JLabel lblNewCost;
    private javax.swing.JLabel lblNewCost1;
    private javax.swing.JLabel lblNewCost2;
    private javax.swing.JLabel lblNewDiscount;
    private javax.swing.JLabel lblNewInvoiceDesc;
    private javax.swing.JLabel lblNewInvoiceNo;
    private javax.swing.JLabel lblNewItemMain;
    private javax.swing.JLabel lblSearchInvoice;
    private javax.swing.JLabel lblSearchInvoiceDate;
    private javax.swing.JLabel lblSearchInvoiceNo;
    private javax.swing.JPanel panelNewItem;
    private javax.swing.JTabbedPane panelSearchInvoice;
    private javax.swing.JTable tblInvoiceDetail;
    private javax.swing.JFormattedTextField txtNewBalance;
    private javax.swing.JFormattedTextField txtNewCost;
    private javax.swing.JTextArea txtNewDesc;
    private javax.swing.JFormattedTextField txtNewDiscount;
    private javax.swing.JTextField txtNewInvoiceNo;
    private javax.swing.JFormattedTextField txtNewPaidAmount;
    private javax.swing.JTextField txtSearchInvoiceDate;
    private javax.swing.JTextField txtSearchInvoiceNo;
    // End of variables declaration//GEN-END:variables
}
