/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vgates.customerportal.view.invoice;

import com.vgates.customerportal.controller.CustomerDetailController;
import com.vgates.customerportal.controller.MasterInvoiceController;
import com.vgates.customerportal.controller.MasterServiceController;
import com.vgates.customerportal.controller.UserDetailController;
import com.vgates.customerportal.model.CustomerDetail;
import com.vgates.customerportal.model.Invoice;
import com.vgates.customerportal.model.MasterService;
import com.vgates.customerportal.model.UserDetail;
import com.vgates.customerportal.util.MethodResult;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;

/**
 *
 * @author Chamith
 */
public class InvoiceMainForm extends javax.swing.JPanel {

    private final UserDetailController userDetailController;
    private final MasterServiceController serviceController;
    private final CustomerDetailController customerDetailController;
    private final MasterInvoiceController invoiceController;

    private final DefaultTableModel defaultServiceTableModel;
    private final Logger LOGGER = Logger.getLogger(InvoiceMainForm.class);
    private UserDetail userDetail;
    private Invoice invoice;
    private MasterService searchedService;
    private File jasperFile;
    private DefaultTableModel dtm;

    Matcher priceMatcher;
    private final Pattern pattern;
    private List<MasterService> masterServices;

    /**
     * Creates new form InvoiceMainForm
     */
    public InvoiceMainForm() {
        initComponents();
        setSize(800, 550);

        userDetailController = new UserDetailController();
        serviceController = new MasterServiceController();
        invoiceController = new MasterInvoiceController();
        masterServices = new ArrayList<>();
        userDetail = userDetailController.findUserDetailForActiveLogin();
        customerDetailController = new CustomerDetailController();

        defaultServiceTableModel = (DefaultTableModel) tblServiceDetail.getModel();
        defaultServiceTableModel.setRowCount(0);

        txtNewTotalCost.setText("00.00");
        txtNewDiscount.setText("00.00");
        txtNewPaidAmount.setText("00.00");
        txtNewBalance.setText("00.00");
        txtNewFinalAmount.setText("00.00");
        txtNewInvoiceNo.setText("");
        txtNewDesc.setText("");
        txtNewInvoiceNo.setText(invoiceController.newInvoiceNo());

        txtSearchInvoiceDate.setText("");
        txtSearchInvoiceNo.setText("");
        loadServiceList();
        loadCustomerList();
        jasperFile = new File("./reports/InvoiceReport.jasper");
        dtm = (DefaultTableModel) tblInvoiceDetail.getModel();
        pattern = Pattern.compile("^\\d+.\\d?\\d?$");

    }

    private void loadCustomerList() {
        comboCustomer.removeAllItems();
        comboCustomer.addItem("[SELECT]");
        List<CustomerDetail> allActiveCustomerList = customerDetailController.getAllActiveCustomerList();
        allActiveCustomerList.forEach(e -> {
            comboCustomer.addItem(e);
        });
    }

    private void loadServiceList() {
        comboServiceName.removeAllItems();
        comboServiceName.addItem("[SELECT]");
        List<MasterService> serviceList = serviceController.searchAllActiveService();
        serviceList.forEach(e -> {
            comboServiceName.addItem(e);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInvoiceMain = new javax.swing.JLabel();
        panelSearchInvoice = new javax.swing.JTabbedPane();
        panelNewItem = new javax.swing.JPanel();
        lblNewItemMain = new javax.swing.JLabel();
        lblNewInvoiceNo = new javax.swing.JLabel();
        txtNewInvoiceNo = new javax.swing.JTextField();
        lblNewInvoiceDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNewDesc = new javax.swing.JTextArea();
        lblNewCost = new javax.swing.JLabel();
        lblNewDiscount = new javax.swing.JLabel();
        btnCancelAdd = new javax.swing.JButton();
        btnNewInvoice = new javax.swing.JButton();
        lblNewPaidAmount = new javax.swing.JLabel();
        lblNewBalance = new javax.swing.JLabel();
        lblNewService = new javax.swing.JLabel();
        comboServiceName = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServiceDetail = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        lblNewFinalPrice = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();
        btnPrintInvoice = new javax.swing.JButton();
        lblCustomer = new javax.swing.JLabel();
        comboCustomer = new javax.swing.JComboBox();
        txtNewDiscount = new javax.swing.JFormattedTextField();
        txtNewPaidAmount = new javax.swing.JFormattedTextField();
        txtNewBalance = new javax.swing.JFormattedTextField();
        txtNewFinalAmount = new javax.swing.JFormattedTextField();
        txtNewTotalCost = new javax.swing.JFormattedTextField();
        btnRemove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearchInvoiceDate = new javax.swing.JTextField();
        lblSearchInvoiceDate = new javax.swing.JLabel();
        lblSearchInvoiceNo = new javax.swing.JLabel();
        txtSearchInvoiceNo = new javax.swing.JTextField();
        lblSearchInvoice = new javax.swing.JLabel();
        btnFindInvoice = new javax.swing.JButton();
        btnCancelSearchInvoice = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoiceDetail = new javax.swing.JTable();

        lblInvoiceMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInvoiceMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoiceMain.setText("Invoice Details");

        panelSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblNewItemMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewItemMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewItemMain.setText("New Invoice");

        lblNewInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewInvoiceNo.setText("Invoice No");

        txtNewInvoiceNo.setEditable(false);
        txtNewInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewInvoiceNoActionPerformed(evt);
            }
        });

        lblNewInvoiceDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewInvoiceDesc.setText("Description");

        txtNewDesc.setColumns(20);
        txtNewDesc.setRows(5);
        jScrollPane1.setViewportView(txtNewDesc);

        lblNewCost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewCost.setText("Total");

        lblNewDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewDiscount.setText("Discount");

        btnCancelAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        btnNewInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewInvoice.setText("Save Invoice");
        btnNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewInvoiceActionPerformed(evt);
            }
        });

        lblNewPaidAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewPaidAmount.setText("Paid Amount");

        lblNewBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewBalance.setText("Balance");

        lblNewService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewService.setText("Service");

        comboServiceName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboServiceName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[SELECT]" }));
        comboServiceName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboServiceNameItemStateChanged(evt);
            }
        });
        comboServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServiceNameActionPerformed(evt);
            }
        });

        tblServiceDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service", "Description", "Cost", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServiceDetail.setColumnSelectionAllowed(true);
        tblServiceDetail.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblServiceDetail);
        tblServiceDetail.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblNewFinalPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNewFinalPrice.setText("Final Amount");

        lblOutput.setForeground(new java.awt.Color(204, 0, 0));

        btnPrintInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrintInvoice.setText("Print");
        btnPrintInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintInvoiceActionPerformed(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomer.setText("Customer");

        comboCustomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[SELECT]" }));
        comboCustomer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCustomerItemStateChanged(evt);
            }
        });
        comboCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustomerActionPerformed(evt);
            }
        });

        txtNewDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtNewDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewDiscountFocusGained(evt);
            }
        });
        txtNewDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDiscountActionPerformed(evt);
            }
        });
        txtNewDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewDiscountKeyReleased(evt);
            }
        });

        txtNewPaidAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtNewPaidAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNewPaidAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPaidAmountFocusGained(evt);
            }
        });
        txtNewPaidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPaidAmountActionPerformed(evt);
            }
        });
        txtNewPaidAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPaidAmountKeyReleased(evt);
            }
        });

        txtNewBalance.setEditable(false);
        txtNewBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtNewFinalAmount.setEditable(false);
        txtNewFinalAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewFinalAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtNewTotalCost.setEditable(false);
        txtNewTotalCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtNewTotalCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(153, 0, 0));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewItemLayout = new javax.swing.GroupLayout(panelNewItem);
        panelNewItem.setLayout(panelNewItemLayout);
        panelNewItemLayout.setHorizontalGroup(
            panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewItemLayout.createSequentialGroup()
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNewItemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelNewItemLayout.createSequentialGroup()
                                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNewDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNewDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNewTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelNewItemLayout.createSequentialGroup()
                                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNewFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNewPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNewPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNewFinalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))
                    .addGroup(panelNewItemLayout.createSequentialGroup()
                        .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewItemMain, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                            .addGroup(panelNewItemLayout.createSequentialGroup()
                                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNewInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewInvoiceDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelNewItemLayout.createSequentialGroup()
                                        .addComponent(txtNewInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE))
                                    .addGroup(panelNewItemLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewItemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPrintInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(panelNewItemLayout.createSequentialGroup()
                                .addComponent(lblNewService, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelNewItemLayout.createSequentialGroup()
                        .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelNewItemLayout.setVerticalGroup(
            panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewItemMain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewInvoiceNo)
                    .addComponent(txtNewInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(comboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewInvoiceDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewService)
                    .addComponent(comboServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewCost)
                    .addComponent(txtNewTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewDiscount)
                    .addComponent(txtNewDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewFinalPrice)
                    .addComponent(txtNewFinalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPaidAmount)
                    .addComponent(txtNewPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewBalance)
                    .addComponent(txtNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelAdd)
                    .addComponent(btnNewInvoice)
                    .addComponent(btnPrintInvoice))
                .addContainerGap())
        );

        panelSearchInvoice.addTab("New Invoice", panelNewItem);

        txtSearchInvoiceDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchInvoiceDate.setEnabled(false);
        txtSearchInvoiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInvoiceDateActionPerformed(evt);
            }
        });

        lblSearchInvoiceDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchInvoiceDate.setText("Date");

        lblSearchInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearchInvoiceNo.setText("Invoice No");

        txtSearchInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchInvoiceNo.setEnabled(false);
        txtSearchInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInvoiceNoActionPerformed(evt);
            }
        });

        lblSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchInvoice.setText("Search Item Details");

        btnFindInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFindInvoice.setText("Search Item");
        btnFindInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInvoiceActionPerformed(evt);
            }
        });

        btnCancelSearchInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelSearchInvoice.setText("Cancel");
        btnCancelSearchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSearchInvoiceActionPerformed(evt);
            }
        });

        tblInvoiceDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Category", "Description", "Cost", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblInvoiceDetail);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSearchInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSearchInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchInvoiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtSearchInvoiceNo))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSearchInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFindInvoice)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchInvoiceNo)
                    .addComponent(txtSearchInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchInvoiceDate)
                    .addComponent(txtSearchInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindInvoice)
                    .addComponent(btnCancelSearchInvoice))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelSearchInvoice.addTab("Search Invoices", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInvoiceMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelSearchInvoice)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblInvoiceMain, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSearchInvoice))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewInvoiceNoActionPerformed

    }//GEN-LAST:event_txtNewInvoiceNoActionPerformed

    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        clearForm();


    }//GEN-LAST:event_btnCancelAddActionPerformed

    private void btnNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewInvoiceActionPerformed
//        int responce = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this Invoice...?", "New Invoice", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        int responce = JOptionPane.YES_OPTION;
        if (comboCustomer.getSelectedIndex() == 0) {
            lblOutput.setText("Customer Not selected...");
            return;
        }
        if (Double.parseDouble(txtNewFinalAmount.getText()) <= Double.parseDouble(txtNewPaidAmount.getText())) {
//            LOGGER.debug("Enter to if condition");
//            if (responce == JOptionPane.YES_OPTION) {
            invoice = new Invoice();
            invoice.setInvoiceNo(txtNewInvoiceNo.getText());
            invoice.setCreatedDate(new Date());
            invoice.setDescription(txtNewDesc.getText());
            invoice.setTotalAmount(Double.parseDouble(txtNewTotalCost.getText()));
            invoice.setDiscount(Double.parseDouble(txtNewDiscount.getText()));
            invoice.setPaidAmount(Double.parseDouble(txtNewPaidAmount.getText()));
            invoice.setBalanceAmount(Double.parseDouble(txtNewBalance.getText()));
            invoice.setCustomerDetail((CustomerDetail) comboCustomer.getSelectedItem());

            MethodResult result = invoiceController.generateNewInvoice(invoice, masterServices);
            if (result.isOk()) {

                int res = JOptionPane.showConfirmDialog(this, result.getMessage() + "\nDo you want to print the invoice?", "New Invoice", JOptionPane.YES_NO_OPTION);
                if (res == JOptionPane.YES_OPTION) {
                    btnPrintInvoice.doClick();
                }

                clearForm();

            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "New Invoice", JOptionPane.INFORMATION_MESSAGE);
            }
//            }
        } else {
            lblOutput.setText("Invoice cannot continue cause Paid amount not enough");
        }


    }//GEN-LAST:event_btnNewInvoiceActionPerformed

    private void clearForm() {
        txtNewTotalCost.setText("00.00");
        txtNewDiscount.setText("00.00");
        txtNewPaidAmount.setText("00.00");
        txtNewBalance.setText("00.00");
        txtNewFinalAmount.setText("00.00");
        txtNewInvoiceNo.setText("");
        txtNewDesc.setText("");
        comboCustomer.setSelectedIndex(0);
        comboServiceName.setSelectedIndex(0);
        txtNewInvoiceNo.setText(invoiceController.newInvoiceNo());
        invoice = new Invoice();
        masterServices = new ArrayList<>();
        defaultServiceTableModel.setRowCount(0);
    }

    private void txtSearchInvoiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInvoiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInvoiceDateActionPerformed

    private void txtSearchInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInvoiceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInvoiceNoActionPerformed

    private void btnFindInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInvoiceActionPerformed
//        defaultServiceTableModel.setRowCount(0);
//        List<MasterInvoice> invoiceList = invoiceController.searchInvoiceByNameAndCategory(txtSearchInvoiceName.getText(), txtSearchInvoiceDate.getText());
//        if (invoiceList != null) {
//            invoiceList.forEach(e -> {
//                Object rowData[] = {e.getInvoiceName(), e.getCategory(), e.getDescription(), e.getCost(), e.getDiscount()};
//                defaultServiceTableModel.addRow(rowData);
//            });
//        }
    }//GEN-LAST:event_btnFindInvoiceActionPerformed

    private void btnCancelSearchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSearchInvoiceActionPerformed
        defaultServiceTableModel.setRowCount(0);
    }//GEN-LAST:event_btnCancelSearchInvoiceActionPerformed

    private void comboServiceNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboServiceNameItemStateChanged
        if (comboServiceName.getSelectedIndex() != 0) {
            searchedService = (MasterService) comboServiceName.getSelectedItem();
        } else {
            searchedService = null;
        }
    }//GEN-LAST:event_comboServiceNameItemStateChanged

    private void comboServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServiceNameActionPerformed

    }//GEN-LAST:event_comboServiceNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (searchedService != null) {
            masterServices.add(searchedService);
            Object[] rowData = {searchedService.getServiceName(), searchedService.getDescription(), searchedService.getCost(), searchedService.getDiscount()};
            defaultServiceTableModel.addRow(rowData);
            txtNewTotalCost.setText(String.valueOf(Double.parseDouble(txtNewTotalCost.getText()) + searchedService.getCost()));
            txtNewDiscount.setText(String.valueOf(Double.parseDouble(txtNewDiscount.getText()) + searchedService.getDiscount()));
            txtNewFinalAmount.setText(String.valueOf(Double.parseDouble(txtNewFinalAmount.getText()) + searchedService.getCost()));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPrintInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintInvoiceActionPerformed
        if (comboCustomer.getSelectedIndex() == 0) {
            lblOutput.setText("Customer Not selected...");
            return;
        }
        CustomerDetail customer = (CustomerDetail) comboCustomer.getSelectedItem();

        FileInputStream fileInputStream = null;
        try {
            Map<String, Object> param = new HashMap<>();
            fileInputStream = new FileInputStream(jasperFile);
            param.put("CUSTOMER_ID", customer.getCustomerNo());
            param.put("CUSTOMER_NAME", customer.getCustomerName());
            param.put("CUSTOMER_ADDRESS", customer.getAddress());
            param.put("INVOICE_ID", txtNewInvoiceNo.getText());
            param.put("TOTAL_AMOUNT", txtNewTotalCost.getText());
            param.put("FINAL_AMOUNT", txtNewFinalAmount.getText());
            param.put("PAID_AMOUNT", txtNewPaidAmount.getText());
            param.put("DISCOUNT", txtNewDiscount.getText());
            param.put("BALANCE", txtNewBalance.getText());
            JRTableModelDataSource ds = new JRTableModelDataSource(defaultServiceTableModel);
            JasperPrint jp = JasperFillManager.fillReport(fileInputStream, param, ds);
            JasperViewer.viewReport(jp, false);
        } catch (FileNotFoundException | JRException ex) {
            java.util.logging.Logger.getLogger(InvoiceMainForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(InvoiceMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPrintInvoiceActionPerformed

    private void comboCustomerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCustomerItemStateChanged
        lblOutput.setText("");
    }//GEN-LAST:event_comboCustomerItemStateChanged

    private void comboCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCustomerActionPerformed

    private void txtNewDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewDiscountKeyReleased
        Matcher matcher = pattern.matcher(txtNewDiscount.getText());
        if (!matcher.matches()) {
            return;
        }
        txtNewFinalAmount.setText(Double.parseDouble(txtNewTotalCost.getText()) - Double.parseDouble(txtNewDiscount.getText()) + "");
    }//GEN-LAST:event_txtNewDiscountKeyReleased

    private void txtNewPaidAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPaidAmountKeyReleased
        Matcher matcher = pattern.matcher(txtNewPaidAmount.getText());
        if (!matcher.matches()) {
            return;
        }
        txtNewBalance.setText(Double.parseDouble(txtNewPaidAmount.getText()) - Double.parseDouble(txtNewFinalAmount.getText()) + "");
    }//GEN-LAST:event_txtNewPaidAmountKeyReleased

    private void txtNewDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDiscountActionPerformed
        txtNewPaidAmount.requestFocus();
    }//GEN-LAST:event_txtNewDiscountActionPerformed

    private void txtNewDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewDiscountFocusGained
        txtNewDiscount.selectAll();
    }//GEN-LAST:event_txtNewDiscountFocusGained

    private void txtNewPaidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPaidAmountActionPerformed
        btnNewInvoice.doClick();
    }//GEN-LAST:event_txtNewPaidAmountActionPerformed

    private void txtNewPaidAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPaidAmountFocusGained
        txtNewPaidAmount.selectAll();
    }//GEN-LAST:event_txtNewPaidAmountFocusGained

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        final int selectedRow = tblServiceDetail.getSelectedRow();
        defaultServiceTableModel.removeRow(selectedRow);
        masterServices.remove(selectedRow);
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelSearchInvoice;
    private javax.swing.JButton btnFindInvoice;
    private javax.swing.JButton btnNewInvoice;
    private javax.swing.JButton btnPrintInvoice;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox comboCustomer;
    private javax.swing.JComboBox comboServiceName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblInvoiceMain;
    private javax.swing.JLabel lblNewBalance;
    private javax.swing.JLabel lblNewCost;
    private javax.swing.JLabel lblNewDiscount;
    private javax.swing.JLabel lblNewFinalPrice;
    private javax.swing.JLabel lblNewInvoiceDesc;
    private javax.swing.JLabel lblNewInvoiceNo;
    private javax.swing.JLabel lblNewItemMain;
    private javax.swing.JLabel lblNewPaidAmount;
    private javax.swing.JLabel lblNewService;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSearchInvoice;
    private javax.swing.JLabel lblSearchInvoiceDate;
    private javax.swing.JLabel lblSearchInvoiceNo;
    private javax.swing.JPanel panelNewItem;
    private javax.swing.JTabbedPane panelSearchInvoice;
    private javax.swing.JTable tblInvoiceDetail;
    private javax.swing.JTable tblServiceDetail;
    private javax.swing.JFormattedTextField txtNewBalance;
    private javax.swing.JTextArea txtNewDesc;
    private javax.swing.JFormattedTextField txtNewDiscount;
    private javax.swing.JFormattedTextField txtNewFinalAmount;
    private javax.swing.JTextField txtNewInvoiceNo;
    private javax.swing.JFormattedTextField txtNewPaidAmount;
    private javax.swing.JFormattedTextField txtNewTotalCost;
    private javax.swing.JTextField txtSearchInvoiceDate;
    private javax.swing.JTextField txtSearchInvoiceNo;
    // End of variables declaration//GEN-END:variables
}
